blank_issues_enabled: false
contact_links:
  - name: Rudra Sarkar
    url: https://rudra0x01.xyz/
    about: Please share feedback and question regarding this project or you can create issue directly.
